# Generated by Django 5.1 on 2024-09-20 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_payments_link_payments_session_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="payments",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("Awaiting payment", "Ожидает оплаты"),
                    ("Paid successfully", "Успешно оплачено"),
                    ("Payment error", "Ошибка оплаты"),
                ],
                default="Awaiting payment",
                help_text="Выберите статус оплаты",
                verbose_name="Статус оплаты",
            ),
        ),
    ]
