# Generated by Django 5.1 on 2024-09-20 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_payments_payment_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payments",
            name="payment_status",
            field=models.CharField(
                blank=True,
                default="Awaiting payment",
                null=True,
                verbose_name="Статус оплаты",
            ),
        ),
    ]
