# Generated by Django 5.1 on 2024-09-26 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_payments_payment_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="last_login",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Дата последнего входа",
                null=True,
                verbose_name="Дата последнего входа",
            ),
        ),
    ]
