# Generated by Django 5.1 on 2024-09-25 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0004_lesson_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Дата последнего изменения курса"
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Дата последнего изменения урока"
            ),
        ),
    ]
